version: '3.8'

services:
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "1000:1000"
    env_file:
      - ./services/user-service/.env
    networks:
      - app_network

  restaurant-service:
    build:
      context: ./services/restaurant-service
      dockerfile: Dockerfile
    container_name: restaurant-service
    ports:
      - "4000:4000"
    env_file:
      - ./services/restaurant-service/.env
    environment:
      - NOTIFICATION_SERVICE_URL=http://notification-service:2000/api
    networks:
      - app_network

  order-service:
    build:
      context: ./services/order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "3000:3000"
    env_file:
      - ./services/order-service/.env
    environment:
      - NOTIFICATION_SERVICE_URL=http://notification-service:2000/api
    networks:
      - app_network

  notification-service:
    build:
      context: ./services/notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "2000:2000"
    env_file:
      - ./services/notification-service/.env
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
