# SonarCloud project configuration
sonar.organization=asho-1308
sonar.projectKey=asho-1308_ctse-assignment-1
sonar.projectName=CTSE Assignment 1

# Sources to analyze (adjust if needed)
sonar.sources=frontend/src,services
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

# JS/TS settings
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
