name: SonarCloud Scan
on: [push, pull_request]

jobs:
  sonar:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.CTSE }}
        with:
          args: >
            -Dsonar.organization=asho-1308
            -Dsonar.projectKey=asho-1308_ctse-assignment-1
            -Dsonar.host.url=https://sonarcloud.io
